# Generated by Django 4.1.8 on 2023-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHABackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprroved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default='All', max_length=2000),
            preserve_default=False,
        ),
    ]
